import { MigrationInterface, QueryRunner } from 'typeorm';
export class Subscriptions1789240000000 implements MigrationInterface {
  public async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE "subscription_plan" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "code" character varying(64) NOT NULL, "name" character varying(255) NOT NULL, "intervalMonths" integer NOT NULL, "active" boolean NOT NULL DEFAULT true, "productVariantId" integer NOT NULL, CONSTRAINT "PK_subscription_plan" PRIMARY KEY ("id"), CONSTRAINT "UQ_subscription_plan_code" UNIQUE ("code"), CONSTRAINT "FK_subscription_plan_variant" FOREIGN KEY ("productVariantId") REFERENCES "product_variant"("id") ON DELETE RESTRICT)`);
    await q.query(`CREATE INDEX "IDX_subscription_plan_variant" ON "subscription_plan" ("productVariantId")`);
    await q.query(`CREATE TABLE "customer_subscription" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "customerId" integer NOT NULL, "orderId" integer NOT NULL, "orderLineId" integer NOT NULL, "subscriptionIndex" integer NOT NULL DEFAULT 1, "planId" integer NOT NULL, "productVariantId" integer NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "startedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "cancelledAt" TIMESTAMP WITH TIME ZONE, "reminder30SentAt" TIMESTAMP WITH TIME ZONE, "reminder10SentAt" TIMESTAMP WITH TIME ZONE, "reminder3SentAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_customer_subscription" PRIMARY KEY ("id"), CONSTRAINT "UQ_customer_subscription_line_index" UNIQUE ("orderLineId", "subscriptionIndex"), CONSTRAINT "FK_customer_subscription_customer" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE CASCADE, CONSTRAINT "FK_customer_subscription_order" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE, CONSTRAINT "FK_customer_subscription_line" FOREIGN KEY ("orderLineId") REFERENCES "order_line"("id") ON DELETE CASCADE, CONSTRAINT "FK_customer_subscription_plan" FOREIGN KEY ("planId") REFERENCES "subscription_plan"("id") ON DELETE RESTRICT, CONSTRAINT "FK_customer_subscription_variant" FOREIGN KEY ("productVariantId") REFERENCES "product_variant"("id") ON DELETE RESTRICT)`);
    await q.query(`CREATE INDEX "IDX_customer_subscription_customer_status" ON "customer_subscription" ("customerId", "status")`);
  }
  public async down(q: QueryRunner): Promise<void> { await q.query(`DROP TABLE "customer_subscription"`); await q.query(`DROP TABLE "subscription_plan"`); }
}
