import { api, Badge, Button, Input, toast, useMutation, useQuery } from '@vendure/dashboard';
import { graphql } from '@/gql';
import { useState } from 'react';
const plansQuery = graphql(`query LfinfoDashboardPlans { lfinfoSubscriptionPlans { id code name intervalMonths active productVariantId productName variantName } }`) as any;
const variantsQuery = graphql(`query LfinfoDashboardVariants { productVariants(options: { take: 100 }) { items { id name product { name } } } }`) as any;
const savePlan = graphql(`mutation LfinfoDashboardSavePlan($input: CreateOrUpdateSubscriptionPlanInput!) { lfinfoSaveSubscriptionPlan(input: $input) { id code name intervalMonths active productVariantId } }`) as any;
export function SubscriptionPlansPage() {
  const [draft, setDraft] = useState({ code: '', name: '', intervalMonths: '12', productVariantId: '', active: true });
  const plans = useQuery({ queryKey: ['lfinfo-subscription-plans'], queryFn: () => api.query(plansQuery, {}) });
  const variants = useQuery({ queryKey: ['lfinfo-subscription-variants'], queryFn: () => api.query(variantsQuery, {}) });
  const save = useMutation({ mutationFn: (variables: Parameters<typeof api.mutate>[1]) => api.mutate(savePlan, variables as any) });
  const items = plans.data?.lfinfoSubscriptionPlans ?? []; const productVariants = variants.data?.productVariants?.items ?? [];
  async function submit() { const months = Number(draft.intervalMonths); if (!draft.code.trim() || !draft.name.trim() || !draft.productVariantId || !Number.isInteger(months) || months < 1) { toast.error('Complétez le code, le nom, la variante et une période entière.'); return; } try { await save.mutateAsync({ input: { ...draft, intervalMonths: months } }); toast.success('Période enregistrée'); setDraft({ code: '', name: '', intervalMonths: '12', productVariantId: '', active: true }); await plans.refetch(); } catch (e: any) { toast.error(e.message ?? 'Enregistrement impossible'); } }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Abonnements</h1><p className="text-muted-foreground">Définissez ici les périodes et variantes proposées sur la boutique.</p></div><div className="rounded-lg border p-5 space-y-4"><h2 className="font-semibold">Nouvelle période</h2><div className="grid gap-4 md:grid-cols-2"><Input placeholder="Code (ex. ABO-ANNUEL)" value={draft.code} onChange={e => setDraft({ ...draft, code: e.target.value })}/><Input placeholder="Nom affiché" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/><Input type="number" min="1" placeholder="Durée (mois)" value={draft.intervalMonths} onChange={e => setDraft({ ...draft, intervalMonths: e.target.value })}/><select className="h-9 rounded-md border bg-background px-3 text-sm" value={draft.productVariantId} onChange={e => setDraft({ ...draft, productVariantId: e.target.value })}><option value="">Choisir une variante</option>{productVariants.map((v: any) => <option key={v.id} value={v.id}>{v.product?.name} — {v.name}</option>)}</select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.active} onChange={e => setDraft({ ...draft, active: e.target.checked })}/> Disponible sur la boutique</label><Button onClick={submit} disabled={save.isPending}>Créer la période</Button></div><div className="rounded-lg border overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Offre</th><th className="p-3">Variante</th><th className="p-3">Période</th><th className="p-3">État</th></tr></thead><tbody>{items.map((plan: any) => <tr key={plan.id} className="border-b"><td className="p-3"><div className="font-medium">{plan.name}</div><div className="text-muted-foreground">{plan.code}</div></td><td className="p-3">{plan.productName} — {plan.variantName}</td><td className="p-3">{plan.intervalMonths} mois</td><td className="p-3"><Badge>{plan.active ? 'Active' : 'Inactive'}</Badge></td></tr>)}{items.length === 0 && <tr><td className="p-6 text-muted-foreground" colSpan={4}>Aucune période configurée.</td></tr>}</tbody></table></div></div>;
}
